### ISSUE TITLE
Option to hide internal tables in Hasura

### ISSUE THREAD

**Issue by droserasprout** [dipdup-io/dipdup#1097]
Configure Hasura to exclude internal tables from generating a GraphQL API based on a specific naming pattern.
Indexer config should have an option to skip `dipdup_*` tables. And maybe arbitrary ones. Like this:

```yaml
hasura:
  url: ...
  ignore_internal: true
  ignore:
    - some_user_table
```
