### ISSUE TITLE
Issue with certain big_map values

### ISSUE THREAD

**Issue by veqtor** [dipdup-io/dipdup#422]
**Steps to reproduce:**
Create a big map index for KT1XumYAxnPCrDiLU4XLNciZncExAzdEJrua, big map user_roles, ex:

```yaml
spec_version: 1.2
package: test

contracts:
  access_control_mainnet:
    address: KT1XumYAxnPCrDiLU4XLNciZncExAzdEJrua
    typename: access_control

datasources:
  tzkt:
    kind: tzkt
    url: https://api.tzkt.io

indexes:
  my_index:
    kind: big_map
    datasource: tzkt
    skip_history: never
    handlers:
      - callback: on_update_user_roles
        contract: access_control_mainnet
        path: user_roles
```

**What did you expect to happen:**
user_roles_value.py generated class contains value of type Dict[str, int], corresponding to big_map content which is:
big_map(address, map(string, nat))

**What actually happened:**
user_roles_value.py is empty:
```
# generated by datamodel-codegen:
#   filename:  user_roles_value.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class UserRolesValue(BaseModel):
    pass

    class Config:
        extra = Extra.allow
```

### Environment

* **Python version:** 3.10
* **DipDup version or commit hash:** 5.2.2
* **Database engine version:** not applicable 
* **Hasura version:** not applicable
* **Are you in docker?** not applicable
* **Can you reproduce this issue on `master`?** yes
