### ISSUE TITLE
Add filter by contract code hash to operation index

### ISSUE THREAD

**Issue by m-kus** [dipdup-io/dipdup#530]
**What feature would you like to see in DipDup?**

Allow to filter operations by contract code hash instead of spawning template indexes per each new origination.

**Why do you need this feature, what's the use case?**

For cases like TZProfiles.

**Is there a workaround currently?**

Spawn indexes from template in runtime for every new origination where contract has a certain code.

**Configuration spec**
```
contracts:
    a:
       address?: kt1
       code_hash?: kt1 | int
       typename: my_contract_filter

indexes:
   tzp:
       contracts: [ a ]
       handlers:
           - pattern:
                 - destination: a
```

**Implementation notes**
Codegen: prioritize `code_hash` over `address`, check that at least one of these fields exists
Fetcher & matcher: use referenced filter as is, even if both `code_hash` and `address` present
