### ISSUE TITLE
Default (or intermediary) entrypoints are not handled properly

### ISSUE THREAD

**Issue by m-kus** [dipdup-io/dipdup#603]
Сase 1: handling calls to `default` entrypoint

**Steps to reproduce:**

- Take any contract (e.g. https://better-call.dev/mainnet/KT1FdK33JJxrXBWUATBxV87WQRuWkdQ3FvvQ/code)
- Specify "default" entrypoint in the pattern
- Try to codegen & run indexer

**What did you expect to happen:**
DipDup generates types for default entrypoint and sucessfully indexes respectful operations

**What actually happened:**
DipDup failes to generate types

Case 2: catching calls to `default` entrypoint with generic transaction pattern (without destination/entrypoint)

**Steps to reproduce:**

- Take Sirius DEX contract
- Specify the following pattern for handling token to tez swaps:

```yaml
- callback: on_lb_token_to_xtz
        pattern:
          - type: transaction
            destination: <dex_contract>
            entrypoint: tokenToXtz
          - type: transaction
            destination: <token_contract>
            entrypoint: transfer
          - type: transaction
            source: <dex_contract>
          - type: transaction
            source: <dex_contract>
```

- Run dipdup

**What did you expect to happen:**
DipDup catches both swaps that sending tez to implicit and originated contracts.

**What actually happened:**
DipDup only matches swaps with implicit accounts

**Comment by m-kus** [comment]
Fix on TzKT API side: https://github.com/baking-bad/tzkt/pull/142

**Comment by m-kus** [comment]
Still reproduces on Sirius DEX calls (by @TristanAllaire)

Goal: index Sirius DEX token to tez swaps.

Swap can end with transactions sent to either implicit or originated contract:
- Counter 88569585 for an example with a user: https://better-call.dev/mainnet/opg/oowMzbNZ6GfPj9JEDdQaXvMJ7cm93ojxip1erZdhLofZaNUWDic/contents
- Counter 15558159 for an example with a contract: https://better-call.dev/mainnet/opg/opEdDtyvBk2x5K3rpQD7rBKPSw1VbAF1RkX8u7uTJe7LyfD7qCr/contents

In second case the following pattern won't work:

```yaml
- callback: on_lb_token_to_xtz
        pattern:
          - type: transaction
            destination: <dex_contract>
            entrypoint: tokenToXtz
          - type: transaction
            destination: <token_contract>
            entrypoint: transfer
          - type: transaction
            source: <dex_contract>
          - type: transaction
            source: <dex_contract>
```

DipDup just skips all calls to the default entrypoints => this must not happen.
