### ISSUE TITLE
Token transfer index "from_" filter doesn't work

### ISSUE THREAD

**Issue by TristanAllaire** [dipdup-io/dipdup#636]
**Steps to reproduce:**

My config
```yaml
indexes:
  token_transfer_sender:
    kind: token_transfer
    datasource: tzkt_ghostnet
    handlers:
      - callback: on_token_transfer_sender
        from_: my_contract
```

Tested with filter referenced as "from" or "from_"

**What did you expect to happen:**

Trigger the "on_token_transfer_sender" handler whenever a transfer is made from "my_contract"

**What actually happened:**

Triggered the "on_token_transfer_sender" for every token transfers
With or without it, the filter "from_" doesn't work.

Print of the first token_transfer object caught during the handler first execution:
```log
TokenTransferData(id=42991619, level=1, timestamp=datetime.datetime(2022, 1, 25, 15, 3, 39, tzinfo=datetime.timezone.utc), tzkt_token_id=42991617, contract_address='KT1AafHA1C1vk959wvHWBispY9Y2f3fxBUUo', contract_alias=None, token_id=0, standard=<TokenStandard.FA12: 'fa1.2'>, metadata={}, from_alias=None, from_address=None, to_alias=None, to_address='tz1Ke2h7sDdakHJQh8WX4Z372du1KChsksyU', amount=100, tzkt_transaction_id=None, tzkt_origination_id=None, tzkt_migration_id=42991616)
```

### Environment

* **Python version:** 3.9.9
* **DipDup version or commit hash:** 6.5.3
