### ISSUE TITLE
Allow omitting `evm.subsquid` datasource in config

### ISSUE THREAD

**Issue by droserasprout** [dipdup-io/dipdup#926]
Some blockchains can be indexed with DipDup using EVM node(s), but don't have a public Subsquid data lake yet. Currently, such config looks like this:

```yaml
datasources:
  subsquid:
    kind: evm.subsquid
    url: https://ANY_URL_EXISTING_OR_NOT
    node: evm_node
  evm_node:
    kind: evm.node
    ...

indexes:
  evm_index:
    datasource: subsquid
    node_only: True
```

We could allow using `evm.node` datasource(s) directly like it's `IndexDatasource`, omitting `evm.subsquid`. Functionality won't change; just the config syntax.
